config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

    resources :recipes

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ingredients, -> { order "created_at" }
  accepts_nested_attributes_for :ingredients,
    :allow_destroy => true,
    :reject_if     => :all_blank
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new recipe_params
    if @recipe.save
      flash[:notice] = "Successfully created recipe"
      redirect_to recipe_path(@recipe)
    else
      flash[:errors] = @recipe.errors.full_messages
      render :new
    end
  end

  def show
    @recipe = Recipe.find params[:id]
  end

  def edit
    @recipe = Recipe.find params[:id]
  end

  def update
    @recipe = Recipe.find params[:id]

    if @recipe.update recipe_params
      flash[:notice] = "Successfully updated recipe"
      redirect_to recipe_path(@recipe)
    else
      flash[:errors] = @recipe.errors.full_messages
      render :edit
    end
  end

  private

  def recipe_params
    params.require(:recipe).
      permit(
        :name,
        :picture_url,
        :url, :instructions,
        ingredients_attributes: [:id, :food_type, :quantity, :name])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @recipes = Recipe.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def setup_recipe(recipe)
    10.times { recipe.ingredients.build }
    recipe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MealPlanner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>Meal Planner</h1>
  <%= link_to "Recipes", recipes_path %>

  <%= yield %>

</body>
</html>

app/views/recipes/_recipe_form.html.erb
<%= form_for setup_recipe(recipe) do |recipe_form| %>
  <%= recipe_form.label :name %>
  <%= recipe_form.text_field :name %>

  <%= recipe_form.label :picture_url %>
  <%= recipe_form.text_field :picture_url %>

  <%= recipe_form.label :url %>
  <%= recipe_form.text_field :url %>

  <%= recipe_form.label :instructions %>
  <%= recipe_form.text_area :instructions %>
  <br/>


  <h2>Ingredients</h2>
  <div id="ingredients"></div>
  <div class="ingredient-template">
    <%= recipe_form.fields_for :ingredients do |ingredient_fields| %>
        <%= ingredient_fields.label :food_type %>
        <%= ingredient_fields.text_field :food_type %>

        <%= ingredient_fields.label :quantity %>
        <%= ingredient_fields.text_field :quantity %>

        <%= ingredient_fields.label :name %>
        <%= ingredient_fields.text_field :name %>
        <br/>
      <% end %>
  </div>
  <br/>
  <button class="add-ingredient">Add Ingredient</button>

  <br/>
  <%= recipe_form.submit "Submit" %>
<% end %>

<script>
  // var template = document.getElementsByClassName("ingredient-template")[0]
  // template.hidden = true;

  // var addIngredientButton = document.getElementsByClassName("add-ingredient")[0]
  // addIngredientButton.addEventListener("click", function(event) {
  //   event.preventDefault();

  //   template = document.getElementsByClassName("ingredient-template")[0]
  //   clone = template.cloneNode(true)
  //   clone.className = "ingredient"
  //   clone.hidden = false
  //   document.getElementById("ingredients").append(clone)
//  })
</script>

app/views/recipes/edit.html.erb
<h2>Edit recipe</h2>

<%= render "recipe_form", recipe: @recipe %>

app/views/recipes/index.html.erb
<h2>Recipes:</h2>

<%= link_to "Add recipe", new_recipe_path %>

<% if @recipes.empty? %>
  Sorry we don't have any recipes at the minute. Please try again later.
<% else %>

  <ul style="list-style: none">
    <% @recipes.each do |recipe| %>
      <li>
          <h3>
            <%= link_to recipe.name, recipe %>: <%= link_to "Original Recipe", recipe.url %>
          </h3>

          <%= image_tag recipe.picture_url, width: "200px", height: "150px" %>
      </li>
    <% end %>
  </ul>

<% end %>

app/views/recipes/new.html.erb
<h2>New recipe</h2>

<%= form_for @recipe do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :picture_url %>
  <%= f.text_field :picture_url %>

  <%= f.label :url %>
  <%= f.text_field :url %>

  <%= f.label :instructions %>
  <%= f.text_area :instructions %>

  <%= f.submit "Submit" %>
<% end %>

app/views/recipes/show.html.erb
<h3>
  <%= @recipe.name %>: <%= link_to "Original Recipe", @recipe.url %>
</h3>

<%= link_to "Edit", edit_recipe_path(@recipe) %>
<br/>
<%= image_tag @recipe.picture_url, width: "200px", height: "150px" %>
<br/>

Instructions:

<% @recipe.instructions.split("\n").each do |i| %>
  <%= "<p>#{i}</p>".html_safe %>
<% end %>

Ingredients:

<% @recipe.ingredients.each do |i| %>
  <%= "<p>#{i.name}</p>".html_safe %>
<% end %>

app/views/welcome/index.html.erb
<h1>Meal Planner</h1>

<h3>Recipes:</h3>

<% form_for(:meal, date: Date.new(2020, 8, 31) ) do |f| %>
  <%= label_
  <label>Monday 31st August 2020:</label>
<%=